# Business Insights & Root-Cause Analysis

This notebook translates the completed retail revenue analysis into business insights and actionable recommendations.

The analysis focuses on understanding the major revenue decline observed during 2016, identifying its underlying category and product drivers, examining the revenue recovery, and translating the findings into targeted business actions.

## 1. Objective

The objective of this analysis is to:

- establish the major revenue movement observed during 2016,
- identify the categories and products contributing most to the May–August 2016 revenue decline,
- determine whether the decline was driven by sales volume, revenue per unit, or both,
- identify the categories and products contributing most to the August–September 2016 recovery,
- determine the primary drivers of the recovery, and
- translate the findings into actionable business recommendations.

## 2. Business Questions

The analysis seeks to answer the following questions:

1. What was the overall revenue trend during 2016?

2. When did the major revenue decline occur?

3. Which product categories contributed most to the May–August 2016 decline?

4. Which products were the key contributors within those categories?

5. Was the decline driven primarily by lower sales volume, lower revenue per unit, or both?

6. Which product categories contributed most to the August–September 2016 recovery?

7. Which products were the key contributors within those categories?

8. Was the recovery driven primarily by increased sales volume, improved revenue per unit, or both?

9. What business actions should be prioritized based on the identified decline and recovery drivers?

## 3. Load Finalized KPI Results

The KPI analysis and Power BI dashboard were completed in the preceding phases. This notebook does not repeat the underlying SQL analysis.

Instead, the finalized KPI results are used as the evidence base for the business insights and root-cause analysis presented below.

The analysis will focus on:

- overall 2016 revenue performance,
- the May–August 2016 revenue decline,
- category and product-level decline contributors,
- decline drivers based on volume and monetization,
- the August–September 2016 revenue recovery,
- category and product-level recovery contributors, and
- recovery drivers based on volume and monetization.

In [1]:
import pandas as pd
from pathlib import Path

output_path = Path("../data/outputs")

monthly_revenue = pd.read_csv(output_path / "monthly_revenue.csv")
decline_categories = pd.read_csv(output_path / "decline_categories.csv")
decline_products = pd.read_csv(output_path / "decline_products.csv")
decline_drivers = pd.read_csv(output_path / "decline_drivers.csv")
recovery_categories = pd.read_csv(output_path / "recovery_categories.csv")
recovery_products = pd.read_csv(output_path / "recovery_products.csv")
recovery_drivers = pd.read_csv(output_path / "recovery_drivers.csv")

In [2]:
print("Monthly Revenue:", monthly_revenue.shape)
print("Decline Categories:", decline_categories.shape)
print("Decline Products:", decline_products.shape)
print("Decline Drivers:", decline_drivers.shape)
print("Recovery Categories:", recovery_categories.shape)
print("Recovery Products:", recovery_products.shape)
print("Recovery Drivers:", recovery_drivers.shape)

Monthly Revenue: (12, 7)
Decline Categories: (5, 4)
Decline Products: (25, 7)
Decline Drivers: (25, 9)
Recovery Categories: (5, 4)
Recovery Products: (25, 7)
Recovery Drivers: (25, 9)

In [3]:
monthly_revenue.head()

,year,month,month_name,total_revenue,total_units_sold,units_per_transaction,revenue_per_unit
0,2016,1,January,111200.28,14874.370,3.07,7.48
1,2016,2,February,122114.61,15253.710,3.06,8.01
2,2016,3,March,127924.54,15686.100,2.86,8.16
3,2016,4,April,138172.11,16633.486,2.90,8.31
4,2016,5,May,142719.86,18295.257,2.98,7.80

## 4. Establish the Business Anomaly

The 2016 monthly revenue trend shows a clear period of deterioration followed by a strong recovery.

Revenue increased steadily from January through May 2016, reaching its highest monthly level of $142,719.86 in May. Revenue then declined for three consecutive months, falling to $116,908.98 in August.

This represents a decline of $25,810.88 from May to August, or approximately 18.1%.

The decline was followed by a sharp recovery in September, when revenue increased to $141,239.89, representing a 20.81% month-over-month increase.

Therefore, the key business anomaly selected for root-cause analysis is the significant revenue deterioration between May and August 2016, followed by the subsequent recovery in September.

In [4]:
monthly_revenue

,year,month,month_name,total_revenue,total_units_sold,units_per_transaction,revenue_per_unit
0,2016,1,January,111200.28,14874.370,3.07,7.48
1,2016,2,February,122114.61,15253.710,3.06,8.01
2,2016,3,March,127924.54,15686.100,2.86,8.16
3,2016,4,April,138172.11,16633.486,2.90,8.31
4,2016,5,May,142719.86,18295.257,2.98,7.80
5,2016,6,June,131305.35,16120.596,3.09,8.15
6,2016,7,July,120591.97,14296.960,3.06,8.43
7,2016,8,August,116908.98,13901.520,2.99,8.41
8,2016,9,September,141239.89,17399.230,3.04,8.12
9,2016,10,October,140853.51,17801.980,3.14,7.91
10,2016,11,November,132883.33,16683.920,3.05,7.96
11,2016,12,December,152124.19,18677.300,3.07,8.14

## 5. Root-Cause Analysis — Revenue Decline

The May–August 2016 revenue decline is investigated at three levels:

1. **Category level** — identify the categories contributing most to the overall revenue loss.
2. **Product level** — identify the products responsible for the decline within those categories.
3. **Driver level** — determine whether the decline was associated with lower sales volume, lower revenue per unit, or both.

The analysis uses the finalized KPI 6A results from the preceding SQL analysis.

### 5.1 Categories Contributing to the Revenue Decline

The category-level results identify the product categories that contributed most to the May–August 2016 revenue decline.

The focus is on the absolute revenue loss rather than simply the percentage change, allowing the analysis to prioritize categories with the greatest financial impact.

In [6]:
decline_categories

  sku_category  may_revenue  august_revenue  revenue_change
0          LPF      7953.46         6335.34        -1618.12
1          1EO      3577.58         1999.41        -1578.17
2          J4R      3378.94         1955.75        -1423.19
3          0H2      2182.76         1068.78        -1113.98
4          R6E      3408.58         2418.92         -989.66

### 5.2 Key Product Contributors

After identifying the categories with the largest revenue losses, the analysis moves to the product level.

The finalized product-level results identify the top five declining products within each of the major declining categories. This helps determine which specific products were responsible for the category-level deterioration.

In [8]:
decline_products

,sku_category,product_key,sku,may_revenue,august_revenue,revenue_change,product_rank
0,0H2,1933,CZUZX,339.14,118.29,-220.85,1
1,0H2,3216,LQ555,203.04,49.53,-153.51,2
2,0H2,1533,ABFD7,119.72,30.24,-89.48,3
3,0H2,765,51OBI,192.83,114.75,-78.08,4
4,0H2,342,2AJB5,81.00,17.74,-63.26,5
5,1EO,1970,DAIME,436.89,97.09,-339.80,1
6,1EO,3782,PTA6G,312.54,52.09,-260.45,2
7,1EO,1149,7OJDA,192.90,0.00,-192.90,3
8,1EO,2263,F985N,177.76,0.00,-177.76,4
9,1EO,839,5IINF,156.94,0.00,-156.94,5
10,J4R,1363,93JH4,502.50,241.20,-261.30,1
11,J4R,5159,ZE55T,295.13,65.92,-229.21,2
12,J4R,3736,PFUQ1,381.90,180.90,-201.00,3
13,J4R,4039,RGYIH,297.84,114.55,-183.29,4
14,J4R,984,6JXQ3,173.67,21.71,-151.96,5
15,LPF,3491,NOWXS,321.15,32.12,-289.03,1
16,LPF,3447,NFEKU,247.86,0.00,-247.86,2
17,LPF,2717,IH57V,123.69,0.00,-123.69,3
18,LPF,460,31IUT,150.72,50.24,-100.48,4
19,LPF,866,5S43J,275.42,176.05,-99.37,5
20,R6E,325,280WP,309.83,78.52,-231.31,1
21,R6E,2063,DUWYY,223.17,48.14,-175.03,2
22,R6E,59,0DCAY,472.61,298.73,-173.88,3
23,R6E,5186,ZKKMF,123.78,2.78,-121.00,4
24,R6E,546,3JVIP,136.18,72.00,-64.18,5

### 5.3 Decline Drivers: Volume vs. Monetization

The final stage of the decline analysis examines two components of product performance:

- **Sales volume** — measured through units sold.
- **Monetization** — measured through revenue per unit.

Comparing May with August allows the decline to be classified as:

- Volume driven
- Monetization driven
- Volume + Monetization
- No decline driver

This separates the identification of declining products from the underlying evidence explaining how their revenue changed.

In [9]:
decline_drivers

,sku_category,product_key,sku,may_units,august_units,may_revenue_per_unit,august_revenue_per_unit,revenue_change,decline_driver
0,0H2,1933,CZUZX,54.0,19.00,6.28,6.23,-220.85,Both Volume and Monetization
1,0H2,3216,LQ555,24.0,6.00,8.46,8.26,-153.51,Both Volume and Monetization
2,0H2,1533,ABFD7,24.0,6.00,4.99,5.04,-89.48,Volume Driven
3,0H2,765,51OBI,29.0,17.00,6.65,6.75,-78.08,Volume Driven
4,0H2,342,2AJB5,12.0,2.00,6.75,8.87,-63.26,Volume Driven
5,1EO,1970,DAIME,9.0,2.00,48.54,48.55,-339.80,Volume Driven
6,1EO,3782,PTA6G,6.0,1.00,52.09,52.09,-260.45,Volume Driven
7,1EO,1149,7OJDA,3.0,0.00,64.30,NaN,-192.90,No August Sales
8,1EO,2263,F985N,2.0,0.00,88.88,NaN,-177.76,No August Sales
9,1EO,839,5IINF,1.0,0.00,156.94,NaN,-156.94,No August Sales
10,J4R,1363,93JH4,25.0,12.00,20.10,20.10,-261.30,Volume Driven
11,J4R,5159,ZE55T,15.0,3.00,19.68,21.97,-229.21,Volume Driven
12,J4R,3736,PFUQ1,19.0,9.00,20.10,20.10,-201.00,Volume Driven
13,J4R,4039,RGYIH,13.0,5.00,22.91,22.91,-183.29,Both Volume and Monetization
14,J4R,984,6JXQ3,8.0,1.00,21.71,21.71,-151.96,Volume Driven
15,LPF,3491,NOWXS,10.0,1.00,32.12,32.12,-289.03,Volume Driven
16,LPF,3447,NFEKU,6.0,0.00,41.31,NaN,-247.86,No August Sales
17,LPF,2717,IH57V,9.0,0.00,13.74,NaN,-123.69,No August Sales
18,LPF,460,31IUT,6.0,2.00,25.12,25.12,-100.48,Volume Driven
19,LPF,866,5S43J,24.0,15.34,11.48,11.48,-99.37,Volume Driven
20,R6E,325,280WP,16.0,4.00,19.36,19.63,-231.31,Volume Driven
21,R6E,2063,DUWYY,71.0,13.00,3.14,3.70,-175.03,Volume Driven
22,R6E,59,0DCAY,23.0,16.00,20.55,18.67,-173.88,Both Volume and Monetization
23,R6E,5186,ZKKMF,19.0,1.00,6.51,2.78,-121.00,Both Volume and Monetization
24,R6E,546,3JVIP,4.0,2.00,34.05,36.00,-64.18,Volume Driven

## 6. Recovery Analysis

Following the May–August revenue decline, revenue recovered strongly in September 2016.

The recovery is analyzed using the same three-level approach:

1. **Category level** — identify the categories contributing most to the August–September revenue recovery.
2. **Product level** — identify the products responsible for the recovery within those categories.
3. **Driver level** — determine whether the recovery was associated with increased sales volume, improved revenue per unit, or both.

The analysis uses the finalized KPI 6B results from the preceding SQL analysis.

### 6.1 Categories Contributing to the Revenue Recovery

The category-level results identify the product categories that contributed most to the revenue increase between August and September 2016.

The analysis prioritizes categories based on the absolute amount of revenue recovered.

In [10]:
recovery_categories

  sku_category  august_revenue  september_revenue  recovery_amount
0          1EO         1999.41            3892.57          1893.16
1          SJS         6136.17            7655.71          1519.54
2          LPF         6335.34            7838.77          1503.43
3          OXH         3833.80            5287.15          1453.35
4          1L6          570.93            1766.31          1195.38

### 6.2 Key Product Contributors

The analysis then moves from category-level recovery to individual products.

The finalized product-level results identify the top five recovering products within each of the major recovering categories. This shows which products contributed most directly to the September revenue improvement.

In [11]:
recovery_products

,sku_category,product_key,sku,august_revenue,september_revenue,recovery_amount,product_rank
0,1EO,3782,PTA6G,52.09,358.31,306.22,1
1,1EO,1970,DAIME,97.09,388.04,290.95,2
2,1EO,632,4891R,0.00,249.56,249.56,3
3,1EO,1161,7RU0K,0.00,242.61,242.61,4
4,1EO,1102,7C9N2,0.00,165.99,165.99,5
5,1L6,4841,X2QF9,44.92,494.12,449.20,1
6,1L6,5171,ZGWR1,149.87,449.61,299.74,2
7,1L6,3770,PQ5EZ,23.76,187.32,163.56,3
8,1L6,4221,SR20S,45.59,147.42,101.83,4
9,1L6,4590,V95C2,22.79,79.71,56.92,5
10,LPF,3491,NOWXS,32.12,289.04,256.92,1
11,LPF,866,5S43J,176.05,355.85,179.80,2
12,LPF,306,226UR,49.62,198.48,148.86,3
13,LPF,2717,IH57V,0.00,137.12,137.12,4
14,LPF,1664,BA88U,123.32,246.64,123.32,5
15,OXH,1772,BW8YX,354.56,1063.24,708.68,1
16,OXH,1549,AGKFU,387.95,775.93,387.98,2
17,OXH,375,2IA22,131.46,291.09,159.63,3
18,OXH,4231,SU1WQ,123.70,262.88,139.18,4
19,OXH,1736,BNWAF,0.00,93.99,93.99,5
20,SJS,220,1E39O,196.17,980.85,784.68,1
21,SJS,1890,CRXP2,0.00,555.57,555.57,2
22,SJS,647,4BPPU,0.00,350.62,350.62,3
23,SJS,5215,ZS9CZ,105.30,421.20,315.90,4
24,SJS,2754,ISBLS,0.00,304.86,304.86,5

### 6.3 Recovery Drivers: Volume vs. Monetization

The final stage examines the components underlying product-level recovery:

- **Sales volume** — measured through units sold.
- **Monetization** — measured through revenue per unit.

Comparing August with September allows the recovery to be classified as:

- Volume driven
- Monetization driven
- Volume + Monetization
- No recovery driver

This provides evidence for whether the September recovery was primarily associated with increased sales volume, improved revenue per unit, or a combination of both.

In [12]:
recovery_drivers

,sku_category,product_key,sku,august_units,september_units,august_revenue_per_unit,september_revenue_per_unit,recovery_amount,recovery_driver
0,1EO,3782,PTA6G,1.00,7.0,52.09,51.19,306.22,Volume Driven
1,1EO,1970,DAIME,2.00,8.0,48.55,48.51,290.95,Volume Driven
2,1EO,632,4891R,0.00,1.0,NaN,249.56,249.56,New September Sales
3,1EO,1161,7RU0K,0.00,5.0,NaN,48.52,242.61,New September Sales
4,1EO,1102,7C9N2,0.00,1.0,NaN,165.99,165.99,New September Sales
5,1L6,4841,X2QF9,1.00,11.0,44.92,44.92,449.20,Volume Driven
6,1L6,5171,ZGWR1,1.00,3.0,149.87,149.87,299.74,Volume Driven
7,1L6,3770,PQ5EZ,2.00,19.0,11.88,9.86,163.56,Volume Driven
8,1L6,4221,SR20S,3.00,9.0,15.20,16.38,101.83,Both Volume and Monetization
9,1L6,4590,V95C2,1.00,3.0,22.79,26.57,56.92,Both Volume and Monetization
10,LPF,3491,NOWXS,1.00,9.0,32.12,32.12,256.92,Volume Driven
11,LPF,866,5S43J,15.34,31.0,11.48,11.48,179.80,Both Volume and Monetization
12,LPF,306,226UR,3.00,12.0,16.54,16.54,148.86,Volume Driven
13,LPF,2717,IH57V,0.00,10.0,NaN,13.71,137.12,New September Sales
14,LPF,1664,BA88U,4.00,8.0,30.83,30.83,123.32,Volume Driven
15,OXH,1772,BW8YX,2.00,6.0,177.28,177.21,708.68,Volume Driven
16,OXH,1549,AGKFU,7.00,14.0,55.42,55.42,387.98,Both Volume and Monetization
17,OXH,375,2IA22,14.00,31.0,9.39,9.39,159.63,Volume Driven
18,OXH,4231,SU1WQ,8.00,17.0,15.46,15.46,139.18,Both Volume and Monetization
19,OXH,1736,BNWAF,0.00,5.0,NaN,18.80,93.99,New September Sales
20,SJS,220,1E39O,1.00,5.0,196.17,196.17,784.68,Volume Driven
21,SJS,1890,CRXP2,0.00,3.0,NaN,185.19,555.57,New September Sales
22,SJS,647,4BPPU,0.00,2.0,NaN,175.31,350.62,New September Sales
23,SJS,5215,ZS9CZ,1.00,4.0,105.30,105.30,315.90,Volume Driven
24,SJS,2754,ISBLS,0.00,6.0,NaN,50.81,304.86,New September Sales

## 7. Key Business Insights

The finalized analysis identifies several important patterns in the May–August revenue decline and the subsequent August–September recovery.

### 7.1 Revenue Decline Was Concentrated Across Specific Categories

The May–August decline was not evenly distributed across the product portfolio.

The five categories with the largest revenue declines were:

- LPF: $1,618.12 decline
- 1EO: $1,578.17 decline
- J4R: $1,423.19 decline
- 0H2: $1,113.98 decline
- R6E: $989.66 decline

This indicates that a relatively small group of categories accounted for a substantial portion of the identified category-level decline.

### 7.2 Product-Level Decline Was Driven Primarily by Volume

The product-level analysis shows that many of the major declining products experienced substantial reductions in units sold between May and August.

For example:

- DAIME (1EO) declined from 9 to 2 units, resulting in a $339.80 revenue decline.
- PTA6G (1EO) declined from 6 to 1 unit, resulting in a $260.45 decline.
- 93JH4 (J4R) declined from 25 to 12 units, resulting in a $261.30 decline.
- NOWXS (LPF) declined from 10 to 1 unit, resulting in a $289.03 decline.

Several products also recorded no August sales, including 7OJDA, F985N, 5IINF, NFEKU, and IH57V.

The driver analysis therefore provides stronger evidence for a volume-related deterioration than for a broad monetization problem.

### 7.3 Monetization Was Not the Main Decline Pattern

For many declining products, revenue per unit remained stable or changed only slightly between May and August.

This suggests that the observed revenue deterioration was frequently associated with fewer units being sold rather than a broad reduction in revenue generated per unit.

However, some products experienced both lower volume and lower revenue per unit, indicating that monetization contributed to the decline in specific cases.

### 7.4 Recovery Was Led by a Different Set of Categories

The August–September recovery was led by:

- 1EO: $1,893.16 recovery
- SJS: $1,519.54 recovery
- LPF: $1,503.43 recovery
- OXH: $1,453.35 recovery
- 1L6: $1,195.38 recovery

Notably, 1EO and LPF appear in both the decline and recovery analyses, indicating that some categories that weakened during the decline subsequently recovered.

### 7.5 Recovery Was Primarily Volume-Driven

The recovery results show several products increasing their units sold substantially between August and September while maintaining relatively stable revenue per unit.

Examples include:

- 1E39O (SJS): 1 → 5 units, generating $784.68 additional revenue.
- BW8YX (OXH): 2 → 6 units, generating $708.68 additional revenue.
- X2QF9 (1L6): 1 → 11 units, generating $449.20 additional revenue.
- NOWXS (LPF): 1 → 9 units, generating $256.92 additional revenue.

The analysis also identifies several products with no August sales but new September sales, showing that product reactivation contributed to the recovery.

### 7.6 The Decline → Recovery Pattern Suggests a Volume-Focused Business Story

Taken together, the evidence suggests that the major revenue movement during this period was strongly associated with changes in sales volume.

The decline was characterized by substantial reductions in units sold across several key products, while the recovery was characterized by increased unit sales and reactivation of products that had no August sales.

Monetization changes were present for selected products but do not appear to be the dominant pattern across the identified contributors.

## 8. Business Recommendations

The recommendations below are based on the identified category, product, volume, and monetization patterns.

### 8.1 Prioritize High-Impact Declining Products

Products with the largest revenue losses should receive priority for investigation.

Particular attention should be given to products such as:

- DAIME (1EO)
- NOWXS (LPF)
- 93JH4 (J4R)
- PTA6G (1EO)
- CZUZX (0H2)

The objective should be to determine why unit sales declined substantially during the May–August period.

### 8.2 Investigate Products With No August Sales

Products that generated revenue in May but recorded no August sales represent an important operational signal.

Examples include 7OJDA, F985N, 5IINF, NFEKU, and IH57V.

These products should be investigated for possible changes in product availability, demand, distribution, or sales activity.

The available analysis identifies the revenue movement but does not establish the operational reason for the zero August sales, so these factors should be validated using additional business data.

### 8.3 Monitor Volume as an Early-Warning Indicator

Because many of the identified revenue declines were associated with lower units sold, unit volume should be monitored alongside revenue.

A sustained reduction in units sold can provide an earlier signal of product deterioration before the resulting revenue impact becomes significant.

### 8.4 Protect Strong Recovery Contributors

Products that contributed strongly to the September recovery should be monitored to determine whether their improved performance continues.

Examples include:

- 1E39O (SJS)
- BW8YX (OXH)
- X2QF9 (1L6)
- NOWXS (LPF)
- PTA6G (1EO)

These products demonstrated strong increases in September revenue and should be included in ongoing performance monitoring.

### 8.5 Investigate Product Reactivation Opportunities

Several products recorded no August sales but generated revenue again in September.

This suggests that product reactivation contributed to the recovery.

The business should investigate whether similar reactivation opportunities exist among other products that experience temporary periods of zero sales.

### 8.6 Separate Volume and Monetization Decisions

The analysis shows that volume and monetization should not be treated as the same problem.

For volume-driven products, the priority should be understanding the causes of lower unit sales.

For monetization-driven products, the priority should be understanding changes in revenue per unit.

For products affected by both factors, both dimensions should be investigated simultaneously.

### 8.7 Build a Recurring Monitoring Framework

The analysis can be converted into a recurring monitoring framework using:

- Monthly revenue
- Units sold
- Revenue per unit
- Category revenue
- Product revenue
- Product-level revenue change
- Volume change
- Revenue-per-unit change

This would allow the business to identify emerging declines earlier and distinguish volume-related problems from monetization-related problems.

## 9. Executive Summary

The 2016 retail revenue analysis identified a significant deterioration in revenue between May and August, followed by a strong recovery in September.

Revenue reached $142,719.86 in May before declining to $116,908.98 in August, representing a decrease of $25,810.88 (18.1%). Revenue subsequently recovered to $141,239.89 in September, with a 20.81% month-over-month increase.

The root-cause analysis showed that the decline was concentrated across a limited number of product categories and products. The product-level analysis indicated that lower sales volume was a major contributor to the decline, while monetization effects were present for selected products.

The recovery was led by several categories and products that experienced substantial increases in units sold. Product reactivation also contributed to the September improvement, with some products generating sales again after recording no August sales.

Based on these findings, the primary business priorities are to monitor declining product volume, investigate products with temporary periods of zero sales, protect strong recovery contributors, and separately monitor volume and revenue-per-unit changes.

Overall, the analysis demonstrates an end-to-end approach to retail revenue intelligence: identifying a business anomaly, locating the categories and products responsible, diagnosing the underlying performance drivers, and translating the evidence into targeted business actions.